assignment:
  problem_file: data/sort_argument.txt
  solution_file: data/sort_argument.cc
  output_path: output
  intermediate_path: intermediate

proposers:
  system_prompt: prompts/system_proposer.txt
  models:
    - name: claude-3-haiku-20240307
      type: claude
    - name: mistralai/Mistral-7B-Instruct-v0.3
      type: mixtral
    - name: meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
      type: llama
    - name: gpt-4o-mini
      type: gpt

aggregator:
  system_prompt: prompts/system_aggregator.txt
  model:
    name: claude-3-haiku-20240307
    type: claude

annotator:
  system_prompt: prompts/system_annotator.txt
  model:
    name: claude-3-haiku-20240307
    type: claude

parameters:
  - name: efficiency
    prompt_file: prompts/efficiency.txt
  - name: cleanliness
    prompt_file: prompts/cleanliness.txt
  - name: language_conventions
    prompt_file: prompts/language_conventions.txt
  - name: design
    prompt_file: prompts/design.txt
  - name: data_structures
    prompt_file: prompts/data_structures.txt
  - name: memory
    prompt_file: prompts/memory.txt

api_keys:
  anthropic: ${ANTHROPIC_API_KEY}
  openai: ${OPENAI_API_KEY}
  together: ${TOGETHER_API_KEY}
